drop TYPE if exists grocery;

create TYPE grocery as ENUM (
    'Main', 'Snack', 'Lunch', 'Breakfast'
);

drop table if exists shopping_list;

create table shopping_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT not null,
  price MONEY not null,
  date_added TIMESTAMP default (now() at time zone 'UTC'),
  checked BOOLEAN default false,
  category grocery not null
);
